services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ats_sql_server
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password_123_Strong!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ats_api_backend
    restart: unless-stopped
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=ATS_Db;User Id=sa;Password=Password_123_Strong!;TrustServerCertificate=True;MultipleActiveResultSets=true;
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ats_angular_frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - backend

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ats_cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - frontend
      - backend

volumes:
  mssql_data:
